import type { EdgequityAnalysisNote, EdgequityResearchReportNote } from './types.ts';

const UPDATED_AT = '2026-05-20';

const RESEARCH_REPORTS: Record<string, EdgequityResearchReportNote> = {
  NVDA: {
    sourceLabel: 'NVIDIA Q1 FY2027 earnings release, CFO commentary, FY2026 10-K, and Q4 FY2026 transcript',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1045810/000104581026000051/q1fy27cfocommentary.htm',
    earningsTitle: 'Q1 FY2027: NVIDIA turns AI infrastructure demand into record cash flow',
    earningsDate: 'May 20, 2026',
    earningsTakeaways: [
      'NVIDIA reported record Q1 FY2027 revenue of $81.6B, up 85% year over year and 20% sequentially, showing that AI infrastructure demand is still accelerating at massive scale.',
      'Data Center revenue reached $75.2B, up 92% year over year, driven by Blackwell 300 products and strong demand for InfiniBand, Spectrum-X Ethernet, and NVLink.',
      'The most important detail is guidance. NVIDIA guided Q2 FY2027 revenue to $91.0B while assuming no Data Center compute revenue from China, which means the base case does not depend on a China recovery.',
    ],
    businessSummary: [
      'NVIDIA is no longer just a graphics processing unit company. I see it as the default infrastructure platform for artificial intelligence, combining GPUs, networking, systems, software, and developer tools into one full-stack AI factory offering.',
      'The company makes money when customers build and run AI data centers. That includes cloud providers, AI model builders, sovereign AI projects, enterprises, industrial customers, and eventually robotics and physical AI deployments.',
    ],
    coreSegmentTitle: 'Data Center: The AI Factory Platform',
    coreSegmentBody: [
      'Data Center is the entire investment case. In Q1 FY2027, this segment generated $75.2B of revenue, with roughly half from hyperscale customers and the other half from AI clouds, industrial, enterprise, and sovereign customers.',
      'What I find most important is that networking is becoming a larger part of the story. Data Center networking revenue reached $14.8B and grew 199% year over year. As AI clusters get larger, NVIDIA benefits not only from selling GPUs, but also from connecting those GPUs efficiently.',
    ],
    industryContext: [
      'The AI market is moving from model training into large-scale inference. In simple terms, training builds the model, while inference runs the model every time a user asks a question or an agent performs a task. If AI agents become part of daily software workflows, token demand can keep growing for years.',
      'The key investor debate is whether AI capital spending can earn attractive returns for customers. I think NVIDIA remains in the strongest position because its platform helps customers lower cost per token and improve performance per watt, which are the economics that matter most in AI data centers.',
    ],
    moatPoints: [
      { title: 'CUDA Developer Ecosystem', body: 'CUDA remains the software layer that many AI developers optimize for first. This creates switching costs that pure chip benchmarks do not fully capture.' },
      { title: 'Full-Stack Architecture', body: 'NVIDIA sells GPUs, networking, systems, software, and reference architectures together. That makes the company more important than a normal component supplier.' },
      { title: 'Networking Scale', body: 'Large AI clusters need fast chip-to-chip and server-to-server communication. NVIDIA benefits as AI infrastructure scales from individual servers to full data centers.' },
      { title: 'Roadmap Credibility', body: 'The Blackwell to Rubin roadmap gives customers confidence that the platform will continue improving every generation.' },
      { title: 'Cash Flow Power', body: 'Q1 FY2027 free cash flow reached $48.6B, giving NVIDIA enormous flexibility to fund research and development, secure supply, invest in partners, and return capital.' },
    ],
    forecastSummary: 'My base case assumes NVIDIA remains the leading AI infrastructure platform through the Blackwell cycle and begins transitioning customers toward Rubin without a major demand pause. Revenue growth should slow over time because the base is now enormous, but Q2 guidance of $91.0B suggests the current run-rate is still moving higher.',
    valuationNarrative: 'NVDA is not a cheap stock in the traditional value-investing sense. I would call it a high-quality growth stock at a demanding but still defensible valuation. Around the current price near $223, the stock can work if earnings and free cash flow continue compounding, but the margin of safety depends on execution rather than a low multiple.',
    valuationModel: {
      targetYears: 3,
      basePriceTarget: 275,
      bearPriceTarget: 185,
      bullPriceTarget: 340,
      method: 'The price target uses a scenario-based earnings framework rather than a single-point discounted cash flow model. I anchor the base case to continued Data Center growth, mid-70% gross margins, and slower but still strong earnings compounding as Blackwell transitions toward Rubin.',
      assumptions: [
        'Base case: Q2 FY2027 guidance of $91.0B becomes the new revenue run-rate, with growth moderating as the revenue base gets larger.',
        'Bear case: AI infrastructure spending slows, gross margin normalizes, and customers push more inference workloads to custom silicon.',
        'Bull case: Rubin extends NVIDIA leadership, networking keeps growing faster than compute, and non-hyperscale AI factory demand becomes a larger mix of revenue.',
        'The China Data Center compute recovery is treated as optional upside, not a requirement for the base case.',
      ],
    },
    riskPoints: [
      { title: 'AI Capex Slowdown', body: 'If cloud providers or AI labs slow infrastructure spending, NVIDIA would feel the impact quickly because the stock already prices in strong future demand.' },
      { title: 'Customer Custom Silicon', body: 'Large customers are investing in internal chips to reduce cost and dependency. NVIDIA can still win on performance and ecosystem, but custom silicon is a real long-term risk.' },
      { title: 'China Restrictions', body: 'NVIDIA assumed no Data Center compute revenue from China in Q2 guidance. That reduces near-term reliance on China, but export controls still limit a large market.' },
      { title: 'Supply Commitment Risk', body: 'Inventory rose to $25.8B and supply-related commitments reached $119.0B. This supports growth if demand stays strong, but it raises risk if the cycle slows.' },
      { title: 'Expectation Risk', body: 'NVIDIA can report excellent numbers and still disappoint investors if expectations move even faster than fundamentals.' },
    ],
    finalVerdict: 'I rate NVIDIA a BUY, but not a buy-at-any-price stock. In my view, it remains the cleanest public-market way to own the AI infrastructure buildout. The three metrics I would monitor from here are Data Center networking growth, non-hyperscale customer growth, and whether supply commitments keep converting into real revenue and free cash flow.',
  },
  MSFT: {
    sourceLabel: 'Microsoft FY2026 Q2 transcript, earnings release, and FMP statements',
    sourceUrl: 'https://www.microsoft.com/en-us/investor/events/fy-2026/earnings-fy-2026-q2',
    earningsTitle: 'FY2026 Q2: Azure and AI keep compounding, capex remains the watch item',
    earningsDate: 'Jan 28, 2026',
    earningsTakeaways: [
      'Revenue and operating income grew at a double-digit pace, with Microsoft Cloud and Azure again leading the story.',
      'Management continued to frame AI agents, Copilot, and Azure infrastructure as one connected platform rather than separate products.',
      'The main investor question is timing: when does AI infrastructure spending translate into visible free cash flow acceleration?',
    ],
    businessSummary: [
      'Microsoft is a diversified software and cloud platform built around Azure, Microsoft 365, Windows, LinkedIn, Dynamics, GitHub, and security. Its advantage is breadth: the company can push AI into enterprise workflows that customers already use daily.',
      'The business has multiple profit engines, which makes the AI capex cycle easier to absorb than it would be for a narrower infrastructure company.',
    ],
    coreSegmentTitle: 'Azure, Microsoft Cloud, and Copilot',
    coreSegmentBody: [
      'Azure is the growth engine and the strategic layer for AI compute. Microsoft is using its OpenAI partnership, internal models, and enterprise distribution to pull AI workloads into Azure.',
      'Copilot is still early as a monetization engine, but the strategic logic is strong: AI becomes a paid productivity layer across Office, security, software development, and business applications.',
    ],
    industryContext: [
      'Enterprise AI adoption is moving from experimentation to deployment. The winners should be platforms that combine compute, data, identity, productivity software, and governance.',
      'Microsoft competes with Amazon and Google in cloud, but its enterprise software footprint gives it a different route to AI monetization.',
    ],
    moatPoints: [
      { title: 'Enterprise Distribution', body: 'Microsoft already owns the workflow surface across productivity, identity, security, and developer tools.' },
      { title: 'Cloud Scale', body: 'Azure gives Microsoft the infrastructure layer needed to monetize AI workloads directly.' },
      { title: 'Switching Costs', body: 'Large enterprises rarely rip out Microsoft systems once they are embedded across users, permissions, and compliance workflows.' },
      { title: 'AI Partner Ecosystem', body: 'The OpenAI relationship and Azure model catalog both expand Microsoft’s AI relevance.' },
      { title: 'Financial Resilience', body: 'High margins and recurring revenue reduce the risk of temporary capex pressure.' },
    ],
    forecastSummary: 'The base case assumes Azure keeps growing faster than the broader cloud market and Copilot monetization builds gradually rather than instantly. Operating leverage should remain strong, though free cash flow may lag earnings while AI capex is elevated.',
    valuationNarrative: 'MSFT trades at a premium because the earnings quality is unusually high. The multiple is defensible if Azure growth and AI monetization stay visible, but the stock has less room for disappointment than cheaper software peers.',
    riskPoints: [
      { title: 'AI Capex Timing', body: 'Infrastructure spending can pressure cash conversion before AI revenue fully matures.' },
      { title: 'Cloud Competition', body: 'AWS and Google Cloud remain aggressive competitors for AI workloads.' },
      { title: 'Copilot Adoption Risk', body: 'If Copilot usage is broad but paid conversion is slower than expected, the AI upside may take longer to show in revenue.' },
      { title: 'Regulatory Risk', body: 'Microsoft’s AI partnerships and software bundling can attract antitrust scrutiny.' },
      { title: 'Valuation Risk', body: 'A premium multiple leaves the stock exposed to multiple compression if growth slows.' },
    ],
    finalVerdict: 'Microsoft is still one of the cleanest AI compounders because it owns both cloud infrastructure and enterprise distribution. I would frame it as a BUY at the right price, with AI capex ROI as the metric to monitor.',
  },
  AAPL: {
    sourceLabel: 'Apple Q1 FY2026 transcript sources and FMP statements',
    sourceUrl: 'https://stockanalysis.com/stocks/aapl/transcripts/',
    earningsTitle: 'Q1 FY2026: iPhone strength stabilizes the story while AI remains the open question',
    earningsDate: 'Jan 29, 2026',
    earningsTakeaways: [
      'Apple delivered a record holiday quarter, with iPhone and Services again carrying the financial profile.',
      'Management commentary emphasized product demand and future AI features, but investors still need clearer proof that Apple Intelligence can drive a new upgrade cycle.',
      'The business remains a free cash flow machine, but growth is slower than the mega-cap AI infrastructure names.',
    ],
    businessSummary: [
      'Apple sells premium devices and services built around the iPhone ecosystem. Hardware creates the installed base, while Services increases monetization and margin durability.',
      'The investment case is not explosive growth. It is ecosystem retention, pricing power, cash returns, and optionality from AI-enabled devices.',
    ],
    coreSegmentTitle: 'iPhone, Services, and the Installed Base',
    coreSegmentBody: [
      'The iPhone remains the anchor product because it drives upgrades, accessories, App Store activity, subscriptions, and customer retention.',
      'Services is the margin stabilizer. Even when hardware cycles are uneven, recurring services revenue helps protect profitability and cash flow.',
    ],
    industryContext: [
      'Premium smartphones are a mature market, so the key is replacement cycle strength and incremental monetization rather than unit growth alone.',
      'AI could become the next device-cycle catalyst, but Apple needs to prove that on-device and private AI features are enough to change consumer behavior.',
    ],
    moatPoints: [
      { title: 'Ecosystem Lock-In', body: 'Hardware, software, services, wearables, and payments reinforce one another and reduce churn.' },
      { title: 'Brand Pricing Power', body: 'Apple can sustain premium pricing because customers value design, privacy, and integration.' },
      { title: 'Services Margin', body: 'The Services mix supports profitability even when hardware growth slows.' },
      { title: 'Capital Returns', body: 'Large free cash flow funds one of the most consistent buyback programs in the market.' },
      { title: 'Device AI Optionality', body: 'If Apple Intelligence improves the upgrade cycle, the installed base can become a powerful AI distribution channel.' },
    ],
    forecastSummary: 'The base case assumes low-to-mid single-digit revenue growth, continued Services mix expansion, and steady buybacks. Upside requires a stronger AI-enabled iPhone cycle or new product category contribution.',
    valuationNarrative: 'AAPL deserves a quality premium, but the multiple is harder to justify if revenue growth remains modest. FCF yield and buybacks matter more than headline growth.',
    riskPoints: [
      { title: 'Slow AI Execution', body: 'Apple risks losing investor mindshare if AI features lag competitors.' },
      { title: 'China Demand', body: 'Regional competition and macro weakness can pressure iPhone growth.' },
      { title: 'Regulatory Pressure', body: 'App Store economics face ongoing scrutiny in major markets.' },
      { title: 'Hardware Cycle Risk', body: 'A weak replacement cycle can flatten revenue despite Services growth.' },
      { title: 'Valuation Risk', body: 'The stock often prices Apple like a faster grower than current fundamentals show.' },
    ],
    finalVerdict: 'Apple is a quality holding, not the most obvious upside setup. I would call it a HOLD-to-BUY depending on entry price, with AI-driven upgrade evidence as the key catalyst.',
  },
  GOOGL: {
    sourceLabel: 'Alphabet Q4 2025 transcript sources, earnings coverage, and FMP statements',
    sourceUrl: 'https://stockanalysis.com/stocks/googl/transcripts/',
    earningsTitle: 'Q4 2025: Search, Cloud, and Gemini keep Alphabet in the AI race',
    earningsDate: 'Feb 4, 2026',
    earningsTakeaways: [
      'Alphabet crossed a major revenue scale threshold, with Search, YouTube, and Cloud all contributing.',
      'Google Cloud growth and Gemini adoption are increasingly important because they prove AI is expanding Alphabet rather than only threatening Search.',
      'Capex is the main debate as Alphabet invests heavily in data centers, TPUs, and AI infrastructure.',
    ],
    businessSummary: [
      'Alphabet is a digital advertising, cloud, and AI platform anchored by Google Search. It also owns YouTube, Android, Google Cloud, DeepMind, Waymo, and a large portfolio of data-rich consumer services.',
      'The thesis is that AI changes the interface of search and cloud, but Alphabet has the data, distribution, model capability, and infrastructure to remain one of the main winners.',
    ],
    coreSegmentTitle: 'Search, YouTube, Google Cloud, and Gemini',
    coreSegmentBody: [
      'Search remains the profit engine. AI Overviews and Gemini create risk because user behavior changes, but they also create new ad surfaces and more complex query opportunities.',
      'Google Cloud is the growth validator. If Cloud keeps accelerating with AI workloads, investors can underwrite Alphabet as more than an advertising company.',
    ],
    industryContext: [
      'AI is reshaping information retrieval, advertising, and cloud infrastructure at the same time. That puts Alphabet directly in both the opportunity and the risk zone.',
      'The market is watching whether AI answer engines reduce search monetization or expand it through higher engagement and better intent capture.',
    ],
    moatPoints: [
      { title: 'Search Distribution', body: 'Google remains the default starting point for global information discovery.' },
      { title: 'Data Advantage', body: 'Search, YouTube, Maps, Android, and Chrome provide unmatched behavioral and content signals.' },
      { title: 'AI Infrastructure', body: 'TPUs and Google’s data center footprint give it a vertically integrated AI stack.' },
      { title: 'YouTube Scale', body: 'YouTube is a unique video platform with advertising, subscription, and creator-economy optionality.' },
      { title: 'Balance Sheet Strength', body: 'Net cash and large free cash flow give Alphabet room to invest through the AI cycle.' },
    ],
    forecastSummary: 'The base case assumes Search remains resilient, Cloud grows faster than consolidated revenue, and capex stays elevated while AI infrastructure scales. Margin expansion may pause, but long-term earnings growth remains attractive if AI monetization works.',
    valuationNarrative: 'GOOGL looks more reasonably valued than many mega-cap AI peers. The multiple does not fully price a successful Cloud and Gemini cycle, but capex needs to translate into revenue.',
    riskPoints: [
      { title: 'AI Search Disruption', body: 'If answer engines reduce commercial search clicks, the core profit pool could weaken.' },
      { title: 'Capex Pressure', body: 'AI infrastructure spending can reduce near-term free cash flow and raise depreciation.' },
      { title: 'Regulatory Risk', body: 'Search distribution, ads, and app store practices remain legal pressure points.' },
      { title: 'Cloud Competition', body: 'AWS and Azure remain larger cloud platforms with strong enterprise relationships.' },
      { title: 'Other Bets Dilution', body: 'Moonshot spending can drag margins if monetization remains distant.' },
    ],
    finalVerdict: 'Alphabet is one of the better risk/reward setups in mega-cap tech because the business quality is high and the valuation is not stretched. I would rate it BUY if Search monetization remains intact.',
  },
  AMZN: {
    sourceLabel: 'Amazon Q1 2026 transcript and FMP statements',
    sourceUrl: 'https://www.fool.com/earnings/call-transcripts/2026/04/29/amazon-amzn-q1-2026-earnings-call-transcript/',
    earningsTitle: 'Q1 2026: AWS re-accelerates while retail operating leverage keeps improving',
    earningsDate: 'Apr 29, 2026',
    earningsTakeaways: [
      'Amazon continued to show broad growth, with AWS acceleration and retail efficiency both supporting the thesis.',
      'AI demand is helping AWS, but Amazon is also leaning into custom silicon, Bedrock, and agentic AI services.',
      'The main concern is capital intensity, especially AI infrastructure and satellite investment, which can pressure free cash flow timing.',
    ],
    businessSummary: [
      'Amazon combines a massive retail marketplace, logistics network, advertising business, subscription ecosystem, and AWS cloud platform. The company is unusual because low-margin retail creates scale that supports higher-margin advertising, subscriptions, and cloud.',
      'The thesis depends on AWS growth and retail margin expansion happening at the same time.',
    ],
    coreSegmentTitle: 'AWS, Advertising, and Retail Operating Leverage',
    coreSegmentBody: [
      'AWS is the highest-quality profit pool. AI workloads, Bedrock, custom silicon, and enterprise migration can keep AWS growing faster than Amazon overall.',
      'Retail is no longer only a revenue scale story. Fulfillment efficiency, regionalization, ads, and Prime engagement can drive margin improvement from a very large base.',
    ],
    industryContext: [
      'Cloud infrastructure demand is being reset by AI, while e-commerce keeps shifting toward faster delivery, marketplace breadth, and advertising monetization.',
      'Amazon competes with Microsoft and Google in cloud, Walmart and Costco in retail, and nearly every ad platform in digital advertising.',
    ],
    moatPoints: [
      { title: 'AWS Scale', body: 'AWS has deep enterprise relationships and a broad infrastructure footprint.' },
      { title: 'Marketplace Flywheel', body: 'Selection, sellers, logistics, Prime, and ads reinforce each other.' },
      { title: 'Advertising Growth', body: 'Retail media monetizes purchase intent at high margins.' },
      { title: 'Logistics Network', body: 'Amazon’s fulfillment footprint is difficult to replicate at scale.' },
      { title: 'AI Optionality', body: 'Bedrock, Trainium, and agentic AI services give AWS multiple ways to monetize AI demand.' },
    ],
    forecastSummary: 'The base case assumes AWS growth remains strong, North America margins keep expanding, and international losses continue narrowing. Free cash flow should improve, but capex will remain the key swing factor.',
    valuationNarrative: 'AMZN often screens expensive on P/E because margins are still expanding. P/S, operating income growth, and free cash flow trajectory are more useful than headline earnings alone.',
    riskPoints: [
      { title: 'AI Capex Intensity', body: 'Cloud infrastructure spending can outrun near-term revenue if demand timing slips.' },
      { title: 'Retail Margin Risk', body: 'Competition and fulfillment costs can limit operating leverage.' },
      { title: 'AWS Competition', body: 'Azure and Google Cloud are strong competitors for AI workloads.' },
      { title: 'Regulatory Risk', body: 'Marketplace practices, labor, and antitrust scrutiny remain recurring risks.' },
      { title: 'Project Spending', body: 'Large initiatives such as satellite connectivity can weigh on near-term earnings.' },
    ],
    finalVerdict: 'Amazon is a BUY if AWS acceleration and retail operating leverage remain visible. The business has multiple compounding engines, but free cash flow discipline must stay front and center.',
  },
  META: {
    sourceLabel: 'Meta Q1 2026 official transcript and FMP statements',
    sourceUrl: 'https://s21.q4cdn.com/399680738/files/doc_financials/2026/q1/META-Q1-2026-Earnings-Call-Transcript.pdf',
    earningsTitle: 'Q1 2026: AI improves ads, but infrastructure spending becomes the debate',
    earningsDate: 'Apr 29, 2026',
    earningsTakeaways: [
      'Meta delivered strong revenue growth, driven by engagement, ad pricing, and AI-assisted ranking.',
      'WhatsApp business messaging and AI glasses added optionality, but Family of Apps remains the financial engine.',
      'The market focus is capex: Meta is spending aggressively on AI infrastructure, and investors want clearer monetization timing.',
    ],
    businessSummary: [
      'Meta operates Facebook, Instagram, WhatsApp, Messenger, Threads, Reality Labs, and a growing AI product stack. Advertising remains the main profit pool.',
      'The bull case is that AI improves ad targeting, content recommendations, business messaging, and eventually consumer assistants without breaking the core social graph.',
    ],
    coreSegmentTitle: 'Family of Apps and AI-Driven Advertising',
    coreSegmentBody: [
      'Family of Apps is one of the best cash-flow businesses in the market. AI ranking can raise engagement and improve ad conversion, which makes the core ad business stronger rather than obsolete.',
      'Reality Labs and AI glasses are strategic options, but they are not yet the valuation anchor. The core question is whether AI capex produces better ads and new revenue streams.',
    ],
    industryContext: [
      'Digital advertising is increasingly AI-mediated. Platforms with first-party data, engagement, and advertiser tools should keep gaining budget share.',
      'Meta competes with Google, TikTok, Amazon, Snap, and emerging AI-native interfaces for attention and ad dollars.',
    ],
    moatPoints: [
      { title: 'Global Social Graph', body: 'Meta’s apps reach billions of users and remain deeply embedded in communication and entertainment habits.' },
      { title: 'Ad System Scale', body: 'The ad platform has enormous data, advertiser demand, and optimization feedback loops.' },
      { title: 'AI Ranking', body: 'Better recommendation models can lift engagement and ad relevance.' },
      { title: 'WhatsApp Optionality', body: 'Business messaging creates a large monetization path outside traditional feed ads.' },
      { title: 'Cash Flow Power', body: 'Core app profitability gives Meta room to fund AI and hardware bets.' },
    ],
    forecastSummary: 'The base case assumes ad revenue keeps growing at a healthy pace while AI costs rise. Margins can remain strong, but investors will demand evidence that capex is improving monetization.',
    valuationNarrative: 'META is cheaper than many mega-cap peers relative to growth and margins. The discount exists because Reality Labs losses, regulatory risk, and AI capex create uncertainty.',
    riskPoints: [
      { title: 'AI Capex Risk', body: 'Spending can pressure margins if new AI products do not monetize quickly.' },
      { title: 'Reality Labs Losses', body: 'Hardware and metaverse investment can dilute reported profitability.' },
      { title: 'Regulation', body: 'Privacy, teen safety, and platform governance remain long-running risks.' },
      { title: 'Attention Competition', body: 'TikTok, YouTube, and AI-native apps compete for user time.' },
      { title: 'Ad Cycle Sensitivity', body: 'Meta remains exposed to macro swings in advertising budgets.' },
    ],
    finalVerdict: 'Meta is a BUY if management keeps spending discipline while AI continues improving the ad engine. The core business is excellent, but the capex ramp needs proof.',
  },
  TSLA: {
    sourceLabel: 'Tesla Q1 2026 transcript sources and FMP statements',
    sourceUrl: 'https://tickertrends.io/transcripts/TSLA/Q1-earnings-transcript-2026',
    earningsTitle: 'Q1 2026: Margin stabilization matters more than the long-term robotaxi story',
    earningsDate: 'Apr 2026',
    earningsTakeaways: [
      'Tesla remains an optionality-heavy stock, but the near-term debate is still deliveries, auto gross margin, and capex.',
      'Management continues to point investors toward autonomy, software, robotics, and energy, but current earnings are still mostly tied to vehicle economics.',
      'The stock needs proof that the next growth engine can offset EV pricing pressure.',
    ],
    businessSummary: [
      'Tesla designs and sells electric vehicles, energy storage products, charging infrastructure, software, and autonomy systems. The company’s valuation also embeds future optionality from robotaxis, Optimus, and AI.',
      'The business is transitioning from a pure EV growth story into a more complex platform thesis, but auto margins still dominate current fundamentals.',
    ],
    coreSegmentTitle: 'Automotive Margins, Autonomy, and Energy Storage',
    coreSegmentBody: [
      'Automotive remains the largest revenue source and the biggest risk. Price cuts and competition can quickly pressure margins.',
      'Energy storage and autonomy are the upside levers. Energy is already more visible financially, while autonomy remains more binary and timing-sensitive.',
    ],
    industryContext: [
      'EV adoption is still growing, but competition is intense and pricing power is weaker than it was during the early Tesla growth phase.',
      'Autonomy could change the economics dramatically, but investors need evidence from deployment, regulation, and unit economics.',
    ],
    moatPoints: [
      { title: 'Brand and Scale', body: 'Tesla remains one of the few EV brands with global scale and strong consumer recognition.' },
      { title: 'Manufacturing Learning Curve', body: 'Vertical integration and process engineering remain strategic assets.' },
      { title: 'Charging Network', body: 'The Supercharger footprint improves the ownership experience and ecosystem control.' },
      { title: 'Energy Storage', body: 'Megapack demand gives Tesla a second industrial growth lane.' },
      { title: 'Autonomy Optionality', body: 'If full self-driving scales commercially, Tesla’s economics could look very different from a traditional automaker.' },
    ],
    forecastSummary: 'The base case assumes vehicle growth is modest, margins stabilize, and energy storage continues scaling. The bull case requires credible autonomy commercialization; the bear case is continued EV price pressure without software monetization.',
    valuationNarrative: 'TSLA screens expensive relative to current auto earnings. The valuation only works if investors assign significant value to autonomy, software, energy, or robotics.',
    riskPoints: [
      { title: 'Auto Margin Pressure', body: 'Competition and pricing can compress margins faster than cost reductions offset them.' },
      { title: 'Demand Cyclicality', body: 'EV demand is sensitive to rates, incentives, and consumer confidence.' },
      { title: 'Autonomy Timing', body: 'The market may keep pushing out commercialization timelines.' },
      { title: 'Execution Risk', body: 'Robotaxi, robotics, and new vehicle programs all require complex execution.' },
      { title: 'Valuation Risk', body: 'The stock can fall sharply if optionality is repriced lower.' },
    ],
    finalVerdict: 'Tesla is a HOLD for fundamentals and a speculative BUY only for investors underwriting autonomy. The report should separate current auto economics from future option value.',
  },
  JPM: {
    sourceLabel: 'JPMorgan Q1 2026 transcript sources and FMP statements',
    sourceUrl: 'https://www.fool.com/earnings/call-transcripts/2026/04/21/jpmorgan-jpm-q1-2026-earnings-call-transcript/',
    earningsTitle: 'Q1 2026: Premium bank quality, but macro and credit cycle still matter',
    earningsDate: 'Apr 21, 2026',
    earningsTakeaways: [
      'JPMorgan continues to show best-in-class scale, deposit strength, and diversified earnings power.',
      'Consumer banking, investment banking, markets, and asset management give the company multiple levers through the cycle.',
      'The key question is whether credit costs and net interest income can stay favorable as the rate cycle evolves.',
    ],
    businessSummary: [
      'JPMorgan Chase is the largest U.S. bank by assets, with leading franchises in consumer banking, credit cards, commercial banking, investment banking, trading, and asset management.',
      'The investment case is quality within financials: superior scale, risk management, deposit franchise, and capital generation.',
    ],
    coreSegmentTitle: 'Consumer Banking, Markets, and Investment Banking',
    coreSegmentBody: [
      'Consumer and community banking provides deposit scale and recurring earnings, while markets and investment banking add upside when capital markets activity improves.',
      'JPMorgan’s advantage is diversification. Weakness in one banking line can be offset by strength in another.',
    ],
    industryContext: [
      'Banks are rate-cycle and credit-cycle businesses. Higher rates can help net interest income but eventually pressure borrowers and deposit costs.',
      'Large banks also benefit from regulation-driven scale advantages, because compliance and liquidity requirements are easier to absorb at JPMorgan’s size.',
    ],
    moatPoints: [
      { title: 'Deposit Franchise', body: 'JPMorgan has a massive, sticky deposit base across consumers and businesses.' },
      { title: 'Scale Economics', body: 'Technology, compliance, and liquidity costs are spread across a huge revenue base.' },
      { title: 'Diversified Revenue', body: 'Consumer banking, markets, investment banking, and asset management reduce reliance on one cycle.' },
      { title: 'Risk Management', body: 'JPMorgan has historically managed credit and liquidity risk better than many peers.' },
      { title: 'Capital Return', body: 'Strong earnings support dividends and buybacks when regulators allow.' },
    ],
    forecastSummary: 'The base case assumes modest loan growth, normalized credit costs, and improving capital markets activity. Upside comes from investment banking recovery and disciplined expense control.',
    valuationNarrative: 'JPM deserves a premium bank multiple because returns and risk controls are stronger than peers. The stock should still be valued with credit cycle humility.',
    riskPoints: [
      { title: 'Credit Cycle', body: 'Loan losses can rise quickly if unemployment or consumer stress increases.' },
      { title: 'Rate Pressure', body: 'Falling rates or higher deposit costs can pressure net interest income.' },
      { title: 'Regulation', body: 'Capital requirements can limit buybacks and reduce returns.' },
      { title: 'Markets Volatility', body: 'Trading and investment banking revenue can swing quarter to quarter.' },
      { title: 'Macro Risk', body: 'Banks are leveraged to economic confidence and liquidity conditions.' },
    ],
    finalVerdict: 'JPMorgan is the quality anchor in U.S. banking. I would rate it BUY for investors who want financial exposure, while watching credit costs and NII trajectory.',
  },
  V: {
    sourceLabel: 'Visa Q2 FY2026 corrected transcript and FMP statements',
    sourceUrl: 'https://s1.q4cdn.com/050606653/files/doc_financials/2026/q2/CORRECTED-TRANSCRIPT_-Visa-Inc-V-US-Q2-2026-Earnings-Call-28-April-2026-5_00-PM-ET-4.pdf',
    earningsTitle: 'Q2 FY2026: Payment volume, transactions, and cross-border keep compounding',
    earningsDate: 'Apr 28, 2026',
    earningsTakeaways: [
      'Visa reported strong revenue and EPS growth, supported by payment volume, processed transactions, and cross-border activity.',
      'The model remains extremely capital-light, with high margins and strong cash conversion.',
      'The main debate is valuation, not business quality.',
    ],
    businessSummary: [
      'Visa operates one of the world’s largest payment networks, connecting consumers, merchants, banks, fintechs, and governments. It earns fees from transaction volume rather than taking credit risk like a bank.',
      'The business benefits from secular cash-to-card and card-to-digital payment migration.',
    ],
    coreSegmentTitle: 'Global Payments Network',
    coreSegmentBody: [
      'Visa’s core drivers are payments volume, processed transactions, cross-border volume, and value-added services.',
      'The network model is powerful because incremental transactions require limited capital, allowing high margins and strong free cash flow.',
    ],
    industryContext: [
      'Payments keep moving from cash to digital formats globally. E-commerce, travel recovery, tap-to-pay, real-time payments, and value-added services all expand the addressable market.',
      'Visa competes with Mastercard, domestic payment rails, account-to-account systems, fintech wallets, and regulation-driven fee pressure.',
    ],
    moatPoints: [
      { title: 'Network Effects', body: 'More cardholders and merchants make the network more valuable for both sides.' },
      { title: 'Brand Trust', body: 'Visa is trusted globally for authorization, fraud management, and reliability.' },
      { title: 'Capital-Light Economics', body: 'Visa does not carry credit risk, which supports high margins.' },
      { title: 'Global Acceptance', body: 'The network is accepted across countries, channels, and use cases.' },
      { title: 'Value-Added Services', body: 'Risk, data, consulting, and fraud tools deepen customer relationships.' },
    ],
    forecastSummary: 'The base case assumes high single-digit to low double-digit revenue growth, stable margins, and continued buybacks. Upside comes from cross-border strength and value-added services.',
    valuationNarrative: 'Visa deserves a premium multiple because the model is predictable and capital-light. The risk is paying too much for consistency.',
    riskPoints: [
      { title: 'Regulation', body: 'Interchange and network fees can face political pressure.' },
      { title: 'Alternative Rails', body: 'Account-to-account and real-time payment systems can pressure parts of the network.' },
      { title: 'Consumer Spending', body: 'Payment volume slows if consumer spending weakens.' },
      { title: 'Cross-Border Cyclicality', body: 'Travel and FX-sensitive volumes can fluctuate.' },
      { title: 'Valuation Risk', body: 'Premium compounders can underperform if growth is merely good rather than excellent.' },
    ],
    finalVerdict: 'Visa is one of the cleanest quality compounders in the market. I would rate it BUY on pullbacks, with regulation and valuation as the main watch items.',
  },
  COST: {
    sourceLabel: 'Costco Q2 FY2026 transcript and FMP statements',
    sourceUrl: 'https://www.fool.com/earnings/call-transcripts/2026/03/05/costco-cost-q2-2026-earnings-call-transcript/',
    earningsTitle: 'Q2 FY2026: Membership flywheel stays strong, valuation remains the debate',
    earningsDate: 'Mar 5, 2026',
    earningsTakeaways: [
      'Costco delivered strong net sales, comp sales, membership fee income, and EPS growth.',
      'Renewal rates remained exceptionally high, reinforcing the durability of the membership model.',
      'The business is excellent, but the stock often prices in near-perfect execution.',
    ],
    businessSummary: [
      'Costco operates a global warehouse club model built around membership, high inventory turns, limited SKUs, low markups, and strong customer loyalty.',
      'The investment case is not high margin. It is trust, traffic, renewal rates, scale purchasing, and recurring membership economics.',
    ],
    coreSegmentTitle: 'Membership, Traffic, and Warehouse Expansion',
    coreSegmentBody: [
      'Membership fee income is the quality layer because it is recurring and high margin. Strong renewal rates show that customers continue to see value in the model.',
      'Warehouse expansion adds growth, while digital comparable sales and international clubs create additional runway.',
    ],
    industryContext: [
      'Retail is structurally competitive, but Costco is one of the few models where low prices strengthen the brand instead of weakening margins permanently.',
      'Consumers trade down during tougher periods, which can help traffic, but food, wage, and logistics costs still matter.',
    ],
    moatPoints: [
      { title: 'Membership Loyalty', body: 'High renewal rates create recurring economics and predictable traffic.' },
      { title: 'Scale Purchasing', body: 'Costco’s buying power supports value perception and member trust.' },
      { title: 'Limited SKU Discipline', body: 'A focused assortment improves inventory turns and operating simplicity.' },
      { title: 'Traffic Flywheel', body: 'Low prices, treasure-hunt merchandising, and membership psychology reinforce frequent visits.' },
      { title: 'International Runway', body: 'New warehouses and overseas growth extend the model beyond the U.S. base.' },
    ],
    forecastSummary: 'The base case assumes steady warehouse growth, high renewal rates, and modest margin improvement. EPS can compound, but valuation limits expected return if the entry multiple is too high.',
    valuationNarrative: 'Costco is a superb business that usually trades at a superb-business multiple. The valuation needs patience because the FCF yield is often low relative to other retailers.',
    riskPoints: [
      { title: 'Valuation Risk', body: 'The stock can underperform if multiple compression offsets steady earnings growth.' },
      { title: 'Thin Retail Margins', body: 'Small cost pressures can matter because operating margins are structurally low.' },
      { title: 'Expansion Execution', body: 'New warehouse productivity and international execution need to stay strong.' },
      { title: 'Consumer Pressure', body: 'Weak spending can affect discretionary categories even if traffic holds up.' },
      { title: 'Membership Saturation', body: 'Mature markets may eventually see slower membership growth.' },
    ],
    finalVerdict: 'Costco is a HOLD-to-BUY depending on valuation. The business quality is elite, but the stock needs a reasonable entry price to make the return profile attractive.',
  },
};

RESEARCH_REPORTS.GOOGL = {
  sourceLabel: 'Alphabet Q1 2026 earnings release, Q1 2026 earnings call transcript, FY2025 Form 10-K, and FMP statements',
  sourceUrl: 'https://s206.q4cdn.com/479360582/files/doc_financials/2026/q1/2026q1-alphabet-earnings-release.pdf',
  earningsTitle: 'Q1 2026: Search monetization stays resilient while Cloud and AI infrastructure scale',
  earningsDate: 'Apr 30, 2026',
  earningsTakeaways: [
    'Alphabet reported Q1 2026 revenue of $109.9B, up 22% year over year, with operating income of $39.7B and a 36.1% operating margin. The important read-through is that AI search features have not broken the core ad engine; Search & other revenue still grew 19%.',
    'Google Cloud revenue reached $20.0B, up 63% year over year, and Cloud operating income reached $6.6B. Backlog grew sharply, which matters because it shows that AI infrastructure demand is not only a consumer-search story; enterprise customers are also committing spend.',
    'Management framed 2026 and 2027 as years of elevated capital investment because demand for internal AI products, Cloud AI, and TPU capacity is above available supply. That makes capex productivity the central issue to monitor after every earnings call.',
  ],
  businessSummary: [
    'Alphabet is the parent company of Google, and the simplest way to understand how Alphabet makes money is to separate the business into three layers: Google Services, Google Cloud, and Other Bets. Google Services contains Search, YouTube, Android, Chrome, Maps, Google Play, devices, subscriptions, and the ad networks. It is the profit engine. Google Cloud sells infrastructure, data analytics, cybersecurity, workspace software, and AI tools to enterprises. Other Bets includes earlier-stage businesses such as Waymo, which may become meaningful over time but still lose money today.',
    'Google Search is not just a website. It is an intent marketplace. A user types a question, product need, travel plan, local search, or commercial problem into Google, and advertisers pay to appear near that high-intent demand. This is why Search has historically generated extraordinary margins: Google does not need to create every piece of content, hold inventory, or run a retail fulfillment network. It organizes information and monetizes the moment when the user is close to making a decision.',
    'YouTube is Alphabet\'s attention platform. It monetizes long-form video, Shorts, connected-TV viewing, creator content, subscriptions, and brand advertising. YouTube is strategically different from Search because the user may not have immediate purchase intent, but the platform controls massive viewing time. That gives Alphabet a second advertising surface and a large subscription funnel through YouTube Premium, YouTube TV, and related services.',
    'Google Cloud is the enterprise growth engine. It matters because Alphabet needs a second large profit pool as Search matures and AI changes how people retrieve information. Cloud revenue comes from compute, storage, databases, analytics, cybersecurity, workspace productivity, Vertex AI, Gemini models, and custom AI infrastructure such as TPUs. In Q1 2026, the Cloud segment showed that this is no longer just a revenue growth story; it is now contributing significant operating income.',
    'The educational takeaway is that Alphabet is not only an advertising company and not only an AI company. It is a distribution, data, compute, and monetization company. The key question is whether the new AI interface expands user activity and enterprise demand faster than it disrupts the classic search-results page.',
  ],
  coreSegmentTitle: 'Google Services, Google Cloud, Gemini, and AI Infrastructure',
  coreSegmentBody: [
    'Google Services is the center of the income statement. In FY2025, Google Services generated $342.7B of revenue and $140.4B of operating income. This segment includes Search, YouTube ads, Google Network, subscriptions, platforms, and devices. Search & other revenue was $224.5B in FY2025, which means Search remains the largest single business line. When analyzing Alphabet, start here: if Search monetization weakens materially, the rest of the company has to work much harder to offset it.',
    'AI changes the Search product because users may get answers directly inside AI Overviews or AI Mode instead of clicking through a traditional list of links. That is the risk. The opportunity is that AI lets Google answer more complicated questions, keep users engaged longer, and create new commercial surfaces around planning, shopping, local search, coding, research, and agent-like tasks. On the Q1 2026 call, management said Search queries and usage grew double digits, AI Overviews reached more than 2B monthly users, and AI Mode had more than 100M monthly active users across the U.S. and India. Those numbers do not prove long-term monetization, but they show that AI features are increasing usage rather than immediately replacing Google.',
    'YouTube should be analyzed as both an ad business and a media platform. Shorts gives Alphabet a short-form competitor to TikTok, connected-TV viewing gives it a living-room ad surface, and subscriptions reduce reliance on pure ad cycles. Management noted that YouTube has led U.S. streaming watch time for more than two years and that Shorts reached roughly 200B daily views. The monetization question is whether Shorts and connected TV can keep improving revenue per minute watched.',
    'Google Cloud is the proof point that Alphabet can sell AI beyond consumer products. In Q1 2026, Cloud revenue grew 63% to $20.0B and operating margin reached 32.9%. That margin may fluctuate because Alphabet is investing heavily and integrating Wiz, but the direction matters: Cloud has moved from loss-making scale investment to a real profit contributor. Backlog of about $462B, up sharply year over year, tells us customers are signing multi-year commitments for compute, data, security, and AI workloads.',
    'Gemini and TPUs are the connective tissue. Gemini is the model family used across Search, Workspace, Android, developer tools, and the consumer Gemini app. TPUs are Google\'s custom AI accelerators. The strategic reason TPUs matter is cost and control: if Google can run internal AI workloads and sell external AI capacity on custom silicon, it may reduce dependence on third-party GPUs and improve long-term infrastructure economics. Management said TPU demand is far above current available capacity, which helps explain why capex is rising.',
  ],
  industryContext: [
    'Alphabet sits at the intersection of three industries that are being rebuilt at once: digital advertising, cloud computing, and AI infrastructure. Digital advertising is shifting toward more automated bidding, better measurement, retail media, creator video, and AI-assisted campaign creation. Cloud computing is shifting from general-purpose migration to AI training, inference, data platforms, security, and agentic applications. Search is shifting from keyword links to generated answers and task completion.',
    'That mix makes Alphabet unusually exposed to both sides of AI disruption. If AI answer engines reduce commercial search clicks, Alphabet risks pressure on its highest-margin profit pool. If Google successfully embeds AI into Search, YouTube, Android, Workspace, and Cloud, AI could deepen the moat by making the products more useful and harder to leave. This is why the same AI trend can be read as both the biggest risk and the biggest opportunity.',
    'The competitive set is broad. Microsoft competes through Bing, Copilot, Azure, GitHub, and Office distribution. Amazon competes in cloud and advertising. Meta competes for ad budgets and attention. OpenAI and other AI-native products compete for user queries. Apple controls valuable mobile distribution. Regulators also matter because search distribution payments, ad-tech practices, app-store rules, and default placement can all affect Alphabet\'s economics.',
    'A practical way to read the industry is to ask four questions after each quarter: Are Search queries still growing? Is AI Overviews usage monetizing without hurting ad load or click quality? Is Google Cloud converting AI demand into backlog and margin? Is capex rising because demand is real, or because Alphabet is defending a threatened position?',
  ],
  moatPoints: [
    { title: 'Search Habit and Distribution', body: 'Google remains the default starting point for many information and commercial queries. Habit, browser placement, Android distribution, and advertiser tooling reinforce one another, although regulation could weaken parts of that distribution advantage.' },
    { title: 'First-Party Data and Intent Signals', body: 'Search, YouTube, Maps, Android, Chrome, Gmail, and Play give Alphabet a broad view of user intent and content engagement. That data helps improve ranking, ad targeting, fraud detection, measurement, and AI product quality.' },
    { title: 'AI Model and Infrastructure Stack', body: 'Alphabet owns DeepMind, Gemini, TPUs, global data centers, and Cloud AI tooling. This vertical stack gives the company more control over cost, model deployment, and product integration than a company that only rents third-party compute.' },
    { title: 'YouTube Creator and Viewer Network', body: 'YouTube benefits from a two-sided network: creators go where viewers are, and viewers go where the content library is. That makes YouTube difficult to replicate even when individual video formats change.' },
    { title: 'Balance Sheet and Cash Flow Capacity', body: 'Alphabet generated $164.7B of operating cash flow and $73.3B of free cash flow in FY2025, even while capex rose sharply. That financial capacity gives management room to fund AI infrastructure, buybacks, dividends, and long-term bets.' },
  ],
  forecastSummary: 'The forecast should be built around three operating drivers rather than one headline growth rate. First, Google Services needs to keep growing because it funds the entire company. Even modest Search growth matters when the revenue base is over $200B. Second, Google Cloud needs to keep converting AI demand into revenue, backlog, and operating profit. Cloud does not need to be larger than Search to matter; it only needs to become a durable second profit pool. Third, capex must eventually show up as higher revenue capacity, lower unit cost, or stronger AI product engagement. In the base case, Search remains resilient, YouTube continues monetizing attention, Cloud grows faster than consolidated revenue, and free cash flow stays strong despite elevated infrastructure spending. In the bear case, AI search lowers monetization, regulators reduce default distribution economics, and capex pushes depreciation higher before revenue catches up. In the bull case, Gemini increases query frequency, Cloud backlog converts cleanly, TPUs improve cost structure, and Waymo becomes a more visible option value.',
  valuationNarrative: 'Alphabet should not be valued like a simple ad company, but it also should not be valued as if every AI investment will automatically create high-return growth. The useful valuation question is what investors are paying for each layer. The mature Search and YouTube layer deserves a high multiple if revenue remains resilient and margins stay strong. The Cloud layer deserves a growth multiple if backlog converts into durable operating income. The Other Bets layer should be treated as option value until losses narrow or revenue becomes material. FMP financials show FY2025 revenue of $403.0B, operating income of $129.2B, net income of $132.2B, operating cash flow of $164.7B, and free cash flow of $73.3B. The stock therefore screens as a highly profitable compounder, but not a low-capex one. The main valuation adjustment is that free cash flow yield can look less impressive while Alphabet is building AI capacity; the investor has to decide whether that capex is defensive spending or productive growth investment.',
  valuationModel: {
    targetYears: 3,
    basePriceTarget: 480,
    bearPriceTarget: 350,
    bullPriceTarget: 620,
    method: 'Base-case price target uses 26x FY2028E EPS of about $18.50. The EPS estimate assumes Alphabet compounds EPS roughly 12% annually from the current earnings base as Search remains resilient, Cloud profit scales, and AI capex keeps free cash flow conversion below the old low-capex profile.',
    assumptions: [
      'Base case: Search and YouTube keep growing, Google Cloud remains a second profit pool, and Gemini/AI Overviews increase usage without materially weakening ad monetization.',
      'Bear case: AI search monetization disappoints, regulation weakens distribution economics, and depreciation from AI capex pressures free cash flow.',
      'Bull case: Cloud backlog converts faster, TPUs improve AI unit economics, and Gemini expands high-intent search and workspace usage.',
    ],
  },
  riskPoints: [
    { title: 'AI Search Monetization', body: 'AI Overviews and AI Mode can increase usage, but they may also change click behavior. The risk is not simply that users ask fewer questions. The risk is that more questions are answered without the same level of commercial monetization. Watch Search revenue growth, ad click quality, advertiser ROI commentary, and management language around AI ad formats.' },
    { title: 'Capital Intensity and Free Cash Flow', body: 'Alphabet is spending heavily on data centers, servers, TPUs, and AI capacity. This can be good if demand is real and utilization stays high. It can be painful if revenue growth slows while depreciation rises. Free cash flow was still large in FY2025, but capex consumed a much higher share of operating cash flow than in earlier years.' },
    { title: 'Regulatory and Distribution Risk', body: 'Search defaults, Android practices, ad-tech rules, app-store economics, and privacy regulation are all ongoing pressure points. Regulation may not destroy the business, but it can reduce distribution advantages, increase compliance costs, or force business-model changes.' },
    { title: 'Cloud Competition', body: 'Google Cloud is growing quickly, but AWS and Azure remain larger platforms with deep enterprise relationships. Alphabet must prove that AI differentiation, data analytics, security, and Workspace integration can keep Cloud growing while margins remain attractive.' },
    { title: 'Other Bets and Execution Risk', body: 'Waymo and other bets create long-term optionality, but they also consume capital and management attention. A good Other Bets outcome can add upside; a poor outcome can keep dragging consolidated margins without changing the core Search thesis.' },
  ],
  finalVerdict: 'Alphabet is best read as a lesson in business-model transition. The company still earns most of its money from Search and advertising, but it is using that cash engine to build Cloud, Gemini, TPUs, and AI-native product surfaces. The report should be used to track whether AI is expanding Alphabet\'s usage and enterprise demand, or merely forcing the company to spend more to defend the old search model. The highest-signal checkpoints are Search monetization, AI Overviews usage, Cloud backlog conversion, operating margin, and free cash flow after capex.',
};

export const EDGEQUITY_RESEARCH_BATCH_TICKERS = Object.keys(RESEARCH_REPORTS).sort();

export const EDGEQUITY_ANALYSIS_NOTES: EdgequityAnalysisNote[] = [
  {
    ticker: 'AAPL',
    quickTake: 'Apple pairs fortress-like cash generation with slower growth, so the story is quality first and upside second.',
    strengths: ['Durable ecosystem supports margins and recurring services revenue.', 'Free cash flow remains deep enough to fund buybacks, dividends, and product investment.'],
    watchItems: ['iPhone replacement cycles can pressure near-term revenue.', 'Premium valuation leaves less room for execution misses.'],
    valuationRead: 'P/E and EV/EBITDA sit above many mature peers, while FCF yield is acceptable for a high-quality compounder.',
    bottomLine: 'Best framed as a quality benchmark where entry price matters more than business survival risk.',
    updatedAt: UPDATED_AT,
    research: RESEARCH_REPORTS.AAPL,
  },
  {
    ticker: 'MSFT',
    quickTake: 'Microsoft remains a high-quality software and cloud platform with unusually broad profit engines.',
    strengths: ['Cloud, productivity, and security create multiple growth lanes.', 'Margins and balance sheet quality are among the strongest in mega-cap tech.'],
    watchItems: ['AI infrastructure spending could pressure cash conversion.', 'High expectations make multiple compression the main risk.'],
    valuationRead: 'P/E, P/S, and EV/EBITDA are rich, but FCF yield reflects unusually resilient earnings quality.',
    bottomLine: 'A clean compounder profile, best judged by whether growth can keep justifying the premium.',
    updatedAt: UPDATED_AT,
    research: RESEARCH_REPORTS.MSFT,
  },
  {
    ticker: 'NVDA',
    quickTake: 'NVIDIA remains the cleanest public-market way to own the AI infrastructure buildout after Q1 FY2027 revenue reached $81.6B and Data Center revenue reached $75.2B.',
    strengths: ['Data Center demand, Blackwell 300 products, and networking are still compounding at exceptional scale.', 'Gross margin near 75% and Q1 free cash flow of $48.6B show rare pricing power and cash conversion.'],
    watchItems: ['AI infrastructure cycles can turn quickly if cloud customers slow capital spending.', 'Inventory, supply commitments, custom silicon, and China restrictions all matter more as expectations rise.'],
    valuationRead: 'The stock is not cheap in a traditional value sense, but the valuation can remain defensible if earnings and free cash flow keep compounding from the new FY2027 run-rate.',
    bottomLine: 'The thesis still works, but investors should monitor Data Center networking growth, non-hyperscale demand, and whether large supply commitments keep converting into revenue.',
    updatedAt: UPDATED_AT,
    research: RESEARCH_REPORTS.NVDA,
  },
  {
    ticker: 'GOOGL',
    quickTake: 'Alphabet is best understood as an intent, attention, cloud, and AI infrastructure company rather than only a search engine.',
    strengths: ['Search, YouTube, Android, Chrome, and Maps create distribution and data advantages.', 'Google Cloud, Gemini, TPUs, and DeepMind give Alphabet a second growth layer beyond advertising.'],
    watchItems: ['AI search must expand usage without weakening commercial monetization.', 'Elevated AI capex needs to convert into Cloud revenue, stronger products, or lower unit costs.'],
    valuationRead: 'The market is paying for an elite core ad business plus Cloud and AI optionality, while discounting some uncertainty around capex, regulation, and AI search behavior.',
    bottomLine: 'Use this report to monitor Search monetization, Cloud backlog conversion, Gemini usage, operating margin, and free cash flow after capex.',
    updatedAt: UPDATED_AT,
    research: RESEARCH_REPORTS.GOOGL,
  },
  {
    ticker: 'AMZN',
    quickTake: 'Amazon is a scale story where retail efficiency and AWS profitability drive the investment case.',
    strengths: ['AWS remains a major profit pool with long-term cloud demand.', 'Retail margins have room to improve as logistics scale matures.'],
    watchItems: ['Capital intensity can weigh on free cash flow.', 'Retail competition keeps consolidated margins thinner than software peers.'],
    valuationRead: 'P/E looks high, but P/S is more reasonable because margins are still expanding from a lower base.',
    bottomLine: 'Most attractive when operating leverage is visible and cash flow conversion is improving.',
    updatedAt: UPDATED_AT,
    research: RESEARCH_REPORTS.AMZN,
  },
  {
    ticker: 'META',
    quickTake: 'Meta offers strong ad economics, high margins, and a shareholder-return story balanced against platform risk.',
    strengths: ['Core apps generate very high operating cash flow.', 'AI ranking tools can improve engagement and ad efficiency.'],
    watchItems: ['Reality Labs spending can dilute reported profitability.', 'Regulatory and platform changes remain recurring risks.'],
    valuationRead: 'P/E and EV/EBITDA are reasonable for the margin profile, while FCF yield is stronger than many growth peers.',
    bottomLine: 'A compelling cash-flow story if spending discipline stays intact.',
    updatedAt: UPDATED_AT,
    research: RESEARCH_REPORTS.META,
  },
  {
    ticker: 'TSLA',
    quickTake: 'Tesla remains a high-optionality company, but current fundamentals are more cyclical than earlier growth expectations implied.',
    strengths: ['Brand, software capability, and manufacturing scale remain strategic assets.', 'Balance sheet flexibility helps through EV demand cycles.'],
    watchItems: ['Auto margins and delivery growth need stabilization.', 'Valuation still assumes meaningful future optionality.'],
    valuationRead: 'P/E and EV/EBITDA are elevated versus current margins, and FCF yield is thin for the risk profile.',
    bottomLine: 'The thesis depends on margin recovery and credible growth beyond core auto sales.',
    updatedAt: UPDATED_AT,
    research: RESEARCH_REPORTS.TSLA,
  },
  {
    ticker: 'JPM',
    quickTake: 'JPMorgan is the quality anchor among banks, with scale, returns, and risk controls standing out.',
    strengths: ['Diversified banking franchises support durable earnings.', 'Capital return and profitability are strong for a large bank.'],
    watchItems: ['Credit costs can rise if the economy weakens.', 'Rate-cycle changes can pressure net interest income.'],
    valuationRead: 'P/E and P/B are reasonable for a premium bank, with earnings yield stronger than most growth stocks.',
    bottomLine: 'A high-quality financial where macro and credit cycle matter more than franchise durability.',
    updatedAt: UPDATED_AT,
    research: RESEARCH_REPORTS.JPM,
  },
  {
    ticker: 'V',
    quickTake: 'Visa is a capital-light payments network with elite margins and steady global transaction growth.',
    strengths: ['Network effects and brand trust support durable economics.', 'Cash conversion is strong because the model needs limited capital.'],
    watchItems: ['Regulation can pressure fees over time.', 'Valuation often embeds a premium for consistency.'],
    valuationRead: 'P/E, P/S, and EV/EBITDA are premium, but margins and FCF quality explain much of that premium.',
    bottomLine: 'A quality compounder where the main debate is price paid, not business strength.',
    updatedAt: UPDATED_AT,
    research: RESEARCH_REPORTS.V,
  },
  {
    ticker: 'JNJ',
    quickTake: 'Johnson & Johnson is a defensive healthcare compounder with steady cash flows and moderate growth.',
    strengths: ['Diversified healthcare exposure lowers single-product risk.', 'Dividend durability is supported by consistent cash generation.'],
    watchItems: ['Litigation and product-cycle risk can affect sentiment.', 'Growth is steadier than spectacular.'],
    valuationRead: 'P/E and EV/EBITDA are moderate, while dividend yield and FCF support the defensive profile.',
    bottomLine: 'Best suited as a stability candidate rather than a high-growth thesis.',
    updatedAt: UPDATED_AT,
  },
  {
    ticker: 'WMT',
    quickTake: 'Walmart is a defensive scale retailer with improving digital and advertising optionality.',
    strengths: ['Everyday-value positioning supports traffic through cycles.', 'Scale gives purchasing and logistics advantages.'],
    watchItems: ['Retail margins are structurally thin.', 'Valuation can look full relative to earnings growth.'],
    valuationRead: 'P/E is high for a low-margin retailer, while P/S looks modest because revenue scale is enormous.',
    bottomLine: 'A resilient operator, but upside depends on margin expansion and newer profit pools.',
    updatedAt: UPDATED_AT,
  },
  {
    ticker: 'KO',
    quickTake: 'Coca-Cola is a classic defensive brand compounder with strong margins and income appeal.',
    strengths: ['Brand portfolio supports pricing power across markets.', 'Cash flow and dividends are highly predictable.'],
    watchItems: ['Volume growth is usually modest.', 'Debt and payout levels limit aggressive reinvestment flexibility.'],
    valuationRead: 'P/E and EV/EBITDA are premium for slow growth, but FCF yield and dividend yield support defensiveness.',
    bottomLine: 'A stability and income profile where valuation discipline remains important.',
    updatedAt: UPDATED_AT,
  },
  {
    ticker: 'COST',
    quickTake: 'Costco is an exceptional retailer with loyalty-driven traffic, but the market prices it like a premium compounder.',
    strengths: ['Membership model creates recurring, high-quality revenue.', 'Traffic and renewal rates reflect strong customer loyalty.'],
    watchItems: ['Margins are intentionally low and operationally sensitive.', 'Valuation leaves little room for disappointment.'],
    valuationRead: 'P/E and EV/EBITDA are rich, while FCF yield is low relative to the premium multiple.',
    bottomLine: 'A superb business that needs patience on valuation.',
    updatedAt: UPDATED_AT,
    research: RESEARCH_REPORTS.COST,
  },
  {
    ticker: 'XOM',
    quickTake: 'Exxon Mobil offers scale, cash returns, and commodity exposure with a stronger balance sheet than many cyclicals.',
    strengths: ['Integrated assets support resilience across energy cycles.', 'Dividend and buyback capacity are backed by large cash flows.'],
    watchItems: ['Oil and gas prices drive earnings volatility.', 'Long-term energy transition risk affects terminal assumptions.'],
    valuationRead: 'P/E and EV/EBITDA are modest, while FCF and dividend yield are central to the valuation case.',
    bottomLine: 'A cash-return energy thesis, not a smooth growth compounder.',
    updatedAt: UPDATED_AT,
  },
  {
    ticker: 'CVX',
    quickTake: 'Chevron is a disciplined energy major with income appeal and lower leverage than many commodity peers.',
    strengths: ['Strong balance sheet supports dividends through cycles.', 'Integrated operations provide cash flow diversity.'],
    watchItems: ['Commodity prices remain the dominant earnings driver.', 'Production growth and capital discipline need monitoring.'],
    valuationRead: 'P/E and EV/EBITDA are modest, and dividend yield makes shareholder return a key part of value.',
    bottomLine: 'A conservative energy exposure where cycle timing still matters.',
    updatedAt: UPDATED_AT,
  },
  {
    ticker: 'AMD',
    quickTake: 'AMD is a semiconductor growth name with AI upside, but margins and scale still trail the category leader.',
    strengths: ['Data-center and accelerator demand can drive multi-year growth.', 'Balance sheet risk is low relative to many cyclicals.'],
    watchItems: ['AI execution must translate into revenue share.', 'Valuation already reflects meaningful growth expectations.'],
    valuationRead: 'P/E and EV/EBITDA are elevated, while FCF yield is thin because investors are paying for future growth.',
    bottomLine: 'A growth thesis that needs sustained data-center traction to justify the multiple.',
    updatedAt: UPDATED_AT,
  },
];

const ANALYSIS_NOTES_BY_TICKER = new Map(EDGEQUITY_ANALYSIS_NOTES.map((note) => [note.ticker, note]));

export function getEdgequityAnalysisNote(ticker: string): EdgequityAnalysisNote | null {
  return ANALYSIS_NOTES_BY_TICKER.get(ticker.toUpperCase()) ?? null;
}
