import assert from "node:assert/strict";
import test from "node:test";

import {
  buildThinStockRecordFromFinnhub,
  buildUniverseFromFinnhubSymbols,
  lineItemsToObject,
} from "./finnhub-raw.ts";
import { buildDolthubSqlUrl, normalizeDolthubStatementValue } from "./dolthub.ts";
import { buildFinnhubUrl, normalizeFinnhubMarketCap } from "./finnhub.ts";

const symbolFixture = [
  { symbol: "AAPL", displaySymbol: "AAPL", description: "Apple Inc", type: "Common Stock", currency: "USD", mic: "XNAS" },
  { symbol: "MSFT", displaySymbol: "MSFT", description: "Microsoft Corp", type: "Common Stock", currency: "USD", mic: "XNAS" },
  { symbol: "SPY", displaySymbol: "SPY", description: "SPDR S&P 500 ETF Trust", type: "ETF", currency: "USD", mic: "ARCX" },
  { symbol: "ABC.WS", displaySymbol: "ABC.WS", description: "ABC Warrant", type: "Warrant", currency: "USD", mic: "XNYS" },
  { symbol: "ABC.U", displaySymbol: "ABC.U", description: "ABC Unit", type: "Unit", currency: "USD", mic: "XNYS" },
  { symbol: "AABB", displaySymbol: "AABB", description: "Asia Broadband Inc", type: "Common Stock", currency: "USD", mic: "OOTC" },
  { symbol: "AAPL", displaySymbol: "AAPL", description: "Apple Duplicate", type: "Common Stock", currency: "USD", mic: "XNAS" },
  { symbol: "BRK.B", displaySymbol: "BRK.B", description: "Berkshire Hathaway Class B", type: "Common Stock", currency: "USD", mic: "XNYS" },
];

const reportedFixture = {
  symbol: "AAPL",
  cik: "320193",
  data: [
    {
      accessNumber: "0000320193-25-000079",
      symbol: "AAPL",
      cik: "320193",
      year: 2025,
      quarter: 0,
      form: "10-K",
      startDate: "2024-09-29 00:00:00",
      endDate: "2025-09-27 00:00:00",
      filedDate: "2025-10-31 00:00:00",
      acceptedDate: "2025-10-31 06:01:26",
      report: {
        ic: [
          { concept: "us-gaap_RevenueFromContractWithCustomerExcludingAssessedTax", unit: "usd", label: "Net sales", value: 416_161_000_000 },
          { concept: "us-gaap_GrossProfit", unit: "usd", label: "Gross margin", value: 195_201_000_000 },
          { concept: "us-gaap_OperatingIncomeLoss", unit: "usd", label: "Operating income", value: 133_050_000_000 },
          { concept: "us-gaap_NetIncomeLoss", unit: "usd", label: "Net income", value: 112_010_000_000 },
          { concept: "us-gaap_WeightedAverageNumberOfDilutedSharesOutstanding", unit: "shares", label: "Shares used in computing diluted earnings per share", value: 15_323_000_000 },
        ],
        bs: [
          { concept: "us-gaap_CashAndCashEquivalentsAtCarryingValue", unit: "usd", label: "Cash and cash equivalents", value: 35_934_000_000 },
          { concept: "us-gaap_Assets", unit: "usd", label: "Total assets", value: 359_241_000_000 },
          { concept: "us-gaap_LongTermDebtCurrent", unit: "usd", label: "Current portion of term debt", value: 9_982_000_000 },
          { concept: "us-gaap_LongTermDebtNoncurrent", unit: "usd", label: "Term debt", value: 78_852_000_000 },
          { concept: "us-gaap_StockholdersEquity", unit: "usd", label: "Total shareholders' equity", value: 73_812_000_000 },
        ],
        cf: [
          { concept: "us-gaap_NetCashProvidedByUsedInOperatingActivities", unit: "usd", label: "Cash generated by operating activities", value: 111_482_000_000 },
          { concept: "us-gaap_PaymentsToAcquirePropertyPlantAndEquipment", unit: "usd", label: "Payments for acquisition of property, plant and equipment", value: 12_715_000_000 },
        ],
      },
    },
  ],
};

test("buildUniverseFromFinnhubSymbols keeps clean unique common stocks", () => {
  const universe = buildUniverseFromFinnhubSymbols(symbolFixture, 10);

  assert.deepEqual(universe.map((stock) => stock.ticker), ["AAPL", "BRK.B", "MSFT"]);
  assert.equal(universe[0]?.name, "Apple Inc");
  assert.equal(universe[0]?.source, "finnhub:stock/symbol");
});

test("buildFinnhubUrl appends token and query params", () => {
  const url = buildFinnhubUrl("/stock/profile2", { symbol: "NVDA" }, "token123");

  assert.equal(url.toString(), "https://finnhub.io/api/v1/stock/profile2?symbol=NVDA&token=token123");
});

test("normalizeFinnhubMarketCap converts Finnhub million-dollar value to dollars", () => {
  assert.equal(normalizeFinnhubMarketCap(5210986.044312), 5_210_986_044_312);
  assert.equal(normalizeFinnhubMarketCap(null), null);
});

test("buildDolthubSqlUrl encodes the SQL query", () => {
  const url = buildDolthubSqlUrl("SELECT * FROM earnings_calendar WHERE act_symbol='NVDA'");

  assert.equal(url.origin, "https://www.dolthub.com");
  assert.equal(url.searchParams.get("q"), "SELECT * FROM earnings_calendar WHERE act_symbol='NVDA'");
});

test("normalizeDolthubStatementValue parses decimal strings", () => {
  assert.equal(normalizeDolthubStatementValue("416161000000"), 416_161_000_000);
  assert.equal(normalizeDolthubStatementValue(null), null);
});

test("lineItemsToObject maps common financial concepts from Finnhub as-reported filings", () => {
  const filing = reportedFixture.data[0]!;
  const mapped = lineItemsToObject(filing.report.ic, filing.report.bs, filing.report.cf);

  assert.equal(mapped.revenue, 416_161_000_000);
  assert.equal(mapped.grossProfit, 195_201_000_000);
  assert.equal(mapped.operatingIncome, 133_050_000_000);
  assert.equal(mapped.netIncome, 112_010_000_000);
  assert.equal(mapped.totalAssets, 359_241_000_000);
  assert.equal(mapped.totalDebt, 88_834_000_000);
  assert.equal(mapped.totalEquity, 73_812_000_000);
  assert.equal(mapped.operatingCashFlow, 111_482_000_000);
  assert.equal(mapped.freeCashFlow, 98_767_000_000);
});

test("buildThinStockRecordFromFinnhub preserves raw source metadata and thin summary metrics", () => {
  const record = buildThinStockRecordFromFinnhub({
    ticker: "AAPL",
    profile: {
      name: "Apple Inc",
      finnhubIndustry: "Technology",
      currency: "USD",
      marketCapitalization: 3_000_000,
      shareOutstanding: 15_500,
    },
    metrics: {
      metric: {
        currentPrice: 190,
        peTTM: 28,
        forwardPE: 24,
        psTTM: 7,
      },
    },
    reported: reportedFixture,
    sourceFetchedAt: "2026-05-21T00:00:00.000Z",
  });

  assert.equal(record.ticker, "AAPL");
  assert.equal(record.marketCap, 3_000_000_000_000);
  assert.equal(record.history.length, 1);
  assert.equal(record.history[0]?.revenue, 416_161_000_000);
  assert.equal(record.cashFlow.freeCashFlow, 98_767_000_000);
  assert.equal(record.sources?.financialsReported.provider, "finnhub");
  assert.equal(record.sources?.financialsReported.status, "ok");
  assert.equal(record.warnings.includes("Thin summary mapped from Finnhub as-reported line items"), true);
});

test("buildThinStockRecordFromFinnhub uses USD market-cap override for foreign primary listings", () => {
  const record = buildThinStockRecordFromFinnhub({
    ticker: "TSM",
    profile: {
      name: "Taiwan Semiconductor Manufacturing Co Ltd",
      finnhubIndustry: "Semiconductors",
      currency: "TWD",
      marketCapitalization: 56_662_563.710938,
    },
    metrics: { metric: { peTTM: 29.37 } },
    reported: { symbol: "TSM", data: [] },
    sourceFetchedAt: "2026-05-21T00:00:00.000Z",
    marketCapUsdOverride: 1_840_000_000_000,
  });

  assert.equal(record.currency, "TWD");
  assert.equal(record.marketCap, 1_840_000_000_000);
  assert.match(record.sources?.summary?.message ?? "", /market cap sourced from USD/);
});
